import sys
import os
import Game

indentcount = 0

def writeline(f, line):
    indent = 4
    for i in range(0, indent * indentcount):
        f.write(" ")
    f.write(line)
    f.write(os.linesep)

def increase_indent_count():
    global indentcount
    indentcount += 1

def decrease_indent_count():
    global indentcount
    indentcount -= 1


def output_to_html(games, file):
    f = open(file, "w")
    writeline(f, "<html>")
    increase_indent_count()
    writeline(f, "<head>")
    increase_indent_count()
    writeline(f, "<title>HFR Steam List</title>")
    writeline(f, "<script src=\"https://code.jquery.com/jquery-1.11.3.min.js\"></script>")
    writeline(f, "<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>")
    writeline(f, "<script src=\"jquery.watable.js\"></script>")
    writeline(f, "<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\"/>")
    writeline(f, "<link href=\"watable.css\" rel=\"stylesheet\"/>")
    #writeline(f, "<style>")
    #increase_indent_count()
    #writeline(f, "table, th, td {")
    #increase_indent_count()
    #writeline(f, "border: 1px solid black;")
    #decrease_indent_count()
    #writeline(f, "}")
    #writeline(f, "th {")
    #increase_indent_count()
    #writeline(f, "white-space: nowrap;")
    #decrease_indent_count()
    #writeline(f, "}")
    #decrease_indent_count()
    #writeline(f, "</style>")
    
    decrease_indent_count()
    writeline(f, "</head>")
    writeline(f, "<body>")
    increase_indent_count()
    writeline(f, "<div id=\"wata\" style=\"width:auto\"></div>")
    
    writeline(f, "<script type=\"text/javascript\">")
    increase_indent_count()
    writeline(f, "$('#wata').WATable({")
    increase_indent_count()
    writeline(f, "debug: false,")
    writeline(f, "filter: true,")
    writeline(f, "sorting: true,")
    writeline(f, "sortEmptyLast: true,")
    writeline(f, "columnPicker: true,")
    writeline(f, "pageSizes: [],")
    writeline(f, "data: getData()")
    decrease_indent_count()
    writeline(f, "}).data('WATable');")
    writeline(f, "")
    writeline(f, "function getData() {")
    increase_indent_count()
    writeline(f, "var cols = {")
    increase_indent_count()
    writeline(f, "name: {")
    increase_indent_count()
    writeline(f, "index: 1,")
    writeline(f, "type: \"string\",")
    writeline(f, "friendly: \"Name\",")
    writeline(f, "format: \"\",")
    writeline(f, "unique: \"true\",")
    writeline(f, "sortOrder: \"asc\",")
    writeline(f, "tooltip: \"The game's name\",")
    writeline(f, "filter: \"\",")
    decrease_indent_count()
    writeline(f, "},")
    writeline(f, "description: {")
    increase_indent_count()
    writeline(f, "index: 2,")
    writeline(f, "type: \"string\",")
    writeline(f, "friendly: \"Description\",")
    writeline(f, "format: \"\",")
    writeline(f, "unique: \"true\",")
    writeline(f, "//sortOrder: \"asc\",")
    writeline(f, "tooltip: \"The game's description\",")
    writeline(f, "filter: \"\",")
    decrease_indent_count()
    writeline(f, "},")
    writeline(f, "dlc: {")
    increase_indent_count()
    writeline(f, "index: 3,")
    writeline(f, "type: \"bool\",")
    writeline(f, "friendly: \"Is this a DLC?\",")
    writeline(f, "format: \"\",")
    writeline(f, "unique: \"false\",")
    writeline(f, "//sortOrder: \"asc\",")
    writeline(f, "tooltip: \"The game's name\",")
    writeline(f, "filter: \"\",")
    decrease_indent_count()
    writeline(f, "},")
    writeline(f, "linux: {")
    increase_indent_count()
    writeline(f, "index: 4,")
    writeline(f, "type: \"string\",")
    writeline(f, "friendly: \"Does it support Linux?\",")
    writeline(f, "format: \"\",")
    writeline(f, "unique: \"false\",")
    writeline(f, "//sortOrder: \"asc\",")
    writeline(f, "//tooltip: \"The game's name\",")
    writeline(f, "filter: \"\",")
    decrease_indent_count()
    writeline(f, "},")
    writeline(f, "price: {")
    increase_indent_count()
    writeline(f, "index: 5,")
    writeline(f, "type: \"string\",")
    writeline(f, "decimals: 2,")
    writeline(f, "friendly: \"Price\",")
    writeline(f, "format: \"\",")
    writeline(f, "unique: \"false\",")
    writeline(f, "//sortOrder: \"asc\",")
    writeline(f, "tooltip: \"The game's price\",")
    writeline(f, "filter: \"\",")
    decrease_indent_count()
    writeline(f, "},")
    writeline(f, "genres: {")
    increase_indent_count()
    writeline(f, "index: 6,")
    writeline(f, "type: \"string\",")
    writeline(f, "friendly: \"Genres\",")
    writeline(f, "format: \"\",")
    writeline(f, "unique: \"false\",")
    writeline(f, "//sortOrder: \"asc\",")
    writeline(f, "tooltip: \"The game's genres\",")
    writeline(f, "filter: \"\",")
    decrease_indent_count()
    writeline(f, "},")
    writeline(f, "date: {")
    increase_indent_count()
    writeline(f, "index: 7,")
    writeline(f, "type: \"string\",")
    writeline(f, "friendly: \"Release Date\",")
    writeline(f, "format: \"\",")
    writeline(f, "unique: \"false\",")
    writeline(f, "//sortOrder: \"asc\",")
    writeline(f, "tooltip: \"The game's release date\",")
    writeline(f, "filter: \"\",")
    decrease_indent_count()
    writeline(f, "},")
    writeline(f, "review: {")
    increase_indent_count()
    writeline(f, "index: 8,")
    writeline(f, "type: \"string\",")
    writeline(f, "friendly: \"Average review\",")
    writeline(f, "format: \"\",")
    writeline(f, "unique: \"false\",")
    writeline(f, "//sortOrder: \"asc\",")
    writeline(f, "tooltip: \"The game's average review\",")
    writeline(f, "filter: \"\",")
    decrease_indent_count()
    writeline(f, "},")
    writeline(f, "count: {")
    increase_indent_count()
    writeline(f, "index: 9,")
    writeline(f, "type: \"string\",")
    writeline(f, "friendly: \"Reviews count\",")
    writeline(f, "format: \"\",")
    writeline(f, "unique: \"false\",")
    writeline(f, "//sortOrder: \"asc\",")
    writeline(f, "tooltip: \"The game's reviews count\",")
    writeline(f, "filter: \"\",")
    decrease_indent_count()
    writeline(f, "}")
    decrease_indent_count()
    writeline(f, "};")
    writeline(f, "")
    writeline(f, "var rows = [];")
    writeline(f, "")
    i = 0
    for gameName in sorted(games):
        game = games[gameName]
        if (game.available == "no"):
            continue
        if (i == 10):
            break
        i += 1
        writeline(f, "var row = {")
        increase_indent_count()
        #if (game.link != ""):
        #    writeline(f, "<td> <a href=\"" + game.link + "\">" + game.name + "</a> <br/>")
        #    writeline(f, "<img src=" + game.image + " width=\"40%\" height=\"40%\"/> ,")
        #else:
        writeline(f, "name: \"" + game.name + "\",")

        writeline(f, "description: \"" + game.description.strip() + "\",")
        writeline(f, "dlc: " + game.is_dlc + ",")
        writeline(f, "linux: \"" + game.is_linux + "\",")
        writeline(f, "price: \"" + game.price + "\",")
        genres = ""
        for genre in iter(game.genres):
            genres = genres + (genre + ", ")
        genres = genres[:-2]
        writeline(f, "genres: \"" + genres + "\",")
        writeline(f, "date: \"" + game.release_date + "\",")
        writeline(f, "review: \"" + game.avg_review + "\",")
        writeline(f, "count: \"" + game.cnt_review + "\",")
        decrease_indent_count()
        writeline(f, "};")
        writeline(f, "rows.push(row);")
    
    writeline(f, "var data = {")
    increase_indent_count()
    writeline(f, "cols: cols,")
    writeline(f, "rows: rows,")
    decrease_indent_count()
    writeline(f, "};")
    writeline(f, "")
    writeline(f, "return data;")
    decrease_indent_count()
    writeline(f, "}")
    decrease_indent_count()
    writeline(f, "</script>")
    
    decrease_indent_count()
    writeline(f, "</body>")
    decrease_indent_count()
    writeline(f, "</html>")
    f.close()
